apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: quay-bridge-operator
webhooks:
  - name: quayintegration.redhatcop.redhat.io
    clientConfig: 
      service:
        namespace: <namespace>
        name: quay-bridge-operator
        path: "/admissionwebhook"
      caBundle: "${CA_BUNDLE}"
    rules: 
    - operations:  [ "CREATE" ]
      apiGroups: [ "build.openshift.io" ]
      apiVersions: ["v1" ]
      resources: [ "builds" ]
    failurePolicy: Fail
    matchPolicy: Exact
    timeoutSeconds: 30
    sideEffects: None
    admissionReviewVersions: [v1beta1]