---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: quay-openshift-registry-operator
  name: quay-openshift-registry-operator
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    name: quay-openshift-registry-operator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-openshift-registry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quay-openshift-registry-operator
  template:
    metadata:
      labels:
        name: quay-openshift-registry-operator
    spec:
      serviceAccountName: quay-openshift-registry-operator
      containers:
        - name: quay-openshift-registry-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - quay-openshift-registry-operator
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "quay-openshift-registry-operator"
          ports:
          - containerPort: 8443
            protocol: TCP
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: certs
              readOnly: true
      serviceAccount:  quay-openshift-registry-operator
      volumes:
        - name: certs
          secret:
            secretName: quay-openshift-registry-operator